version: '3.2'

services:
  db:
    image: mysql:5
    restart: always
    platform: linux/x86_64
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password