version: '3.1'

services:
  mysqldb:
    image: mysql:8.0.26
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    platform: linux/amd64
    ports:
      - 3306:3306

  node:
    image: node:14.17.6
    container_name: node
    command: npm run dev
    working_dir: /home/app
    volumes:
      - ./:/home/app
    tty: true
    ports:
      - 3000:3000 
